/* @unit-ready */
import { workspace } from 'vscode';
import { TemplateLoader } from './template-loader';
import { createFile, deleteFile } from '../test/test-utils-vscode';
import { randomString } from '../test/test-utils';

describe('TemplateLoader', () => {
  describe('workspace trust', () => {
    it('should throw error when loading JS template in untrusted workspace', async () => {
      const templateLoader = new TemplateLoader();
      const mockIsTrusted = jest.spyOn(workspace, 'isTrusted', 'get');
      mockIsTrusted.mockReturnValue(false);

      const { uri } = await createFile(
        'function createNote() { return { filepath: "test.md", content: "test" }; }',
        [`test-template-${randomString()}.js`]
      );

      try {
        await expect(templateLoader.loadTemplate(uri)).rejects.toThrow(
          'JavaScript templates can only be used in trusted workspaces for security reasons'
        );
      } finally {
        await deleteFile(uri);
        mockIsTrusted.mockRestore();
      }
    });

    it('should load JS template successfully in trusted workspace', async () => {
      const templateLoader = new TemplateLoader();
      const mockIsTrusted = jest.spyOn(workspace, 'isTrusted', 'get');
      mockIsTrusted.mockReturnValue(true);

      const jsTemplateContent = `
        function createNote(context) {
          return {
            filepath: 'test-note.md',
            content: '# Test Note\\n\\nGenerated by JS template'
          };
        }
      `;
      const { uri } = await createFile(jsTemplateContent, [
        `test-template-${randomString()}.js`,
      ]);

      try {
        const template = await templateLoader.loadTemplate(uri);
        expect(template.type).toBe('javascript');
        if (template.type !== 'javascript') {
          throw new Error('Expected JavaScript template type');
        }
        expect(template.createNote).toBeDefined();
        expect(typeof template.createNote).toBe('function');
      } finally {
        await deleteFile(uri);
      }
    });

    it('should load markdown template regardless of workspace trust', async () => {
      const templateLoader = new TemplateLoader();
      const mockIsTrusted = jest.spyOn(workspace, 'isTrusted', 'get');
      mockIsTrusted.mockReturnValue(false);

      const mdTemplateContent = `---
name: Test Template
---
# Test Note

This is a markdown template.`;
      const { uri } = await createFile(mdTemplateContent, [
        `test-template-${randomString()}.md`,
      ]);

      try {
        const template = await templateLoader.loadTemplate(uri);
        expect(template.type).toBe('markdown');
        if (template.type !== 'markdown') {
          throw new Error('Expected markdown template type');
        }
        expect(template.content).toBe(mdTemplateContent);
      } finally {
        await deleteFile(uri);
      }
    });
  });
});
