import { NoteLinkDefinition, Resource } from '../core/model/note';
import { Range } from '../core/model/range';
import { createMarkdownReferences } from '../core/services/markdown-provider';
import { FoamWorkspace } from '../core/model/workspace';
import { TextEdit } from '../core/services/text-edit';
import { getLinkDefinitions } from '../core/services/markdown-parser';

export const LINK_REFERENCE_DEFINITION_HEADER = `[//begin]: # "Autogenerated link references for markdown compatibility"`;
export const LINK_REFERENCE_DEFINITION_FOOTER = `[//end]: # "Autogenerated link references"`;

export const generateLinkReferences = async (
  note: Resource,
  currentNoteText: string,
  eol: string,
  workspace: FoamWorkspace,
  includeExtensions: boolean
): Promise<TextEdit[]> => {
  if (!note) {
    return [];
  }

  const lines = currentNoteText.split(eol);
  const nLines = lines.length;

  const updatedWikilinkDefinitions = createMarkdownReferences(
    workspace,
    note,
    includeExtensions
  );

  const existingWikilinkDefinitions = getLinkDefinitions(currentNoteText);

  const toAddWikilinkDefinitions = updatedWikilinkDefinitions.filter(
    newDef =>
      !existingWikilinkDefinitions.some(
        existingDef => existingDef.label === newDef.label
      )
  );
  const toRemovedWikilinkDefinitions = existingWikilinkDefinitions.filter(
    existingDef =>
      !updatedWikilinkDefinitions.some(
        newDef => newDef.label === existingDef.label
      )
  );

  const edits: TextEdit[] = [];

  // Remove old definitions
  for (const def of toRemovedWikilinkDefinitions) {
    edits.push({ range: def.range, newText: '' });
  }

  // Add new definitions
  if (toAddWikilinkDefinitions.length > 0) {
    // find the last non-empty line to append the definitions after it
    const lastLineIndex = nLines - 1;
    let insertLineIndex = lastLineIndex;
    while (insertLineIndex > 0 && lines[insertLineIndex].trim() === '') {
      insertLineIndex--;
    }

    const definitions = toAddWikilinkDefinitions.map(def =>
      NoteLinkDefinition.format(def)
    );
    // Collect labels of wikilinks ([[...]]) in the note. These are the only definitions
    // Foam manages directly — regular [text][ref] link references are user-controlled and
    // should still be followed by a blank line before new wikilink definitions.
    const wikilinkLabels = new Set(
      note.links
        .filter(link => link.type === 'wikilink')
        .map(link =>
          link.rawText.substring(link.isEmbed ? 3 : 2, link.rawText.length - 2)
        )
    );
    // Suppress the double-blank-line prefix when appending to an existing Foam-managed
    // wikilink definition block (i.e., the insertion point already has a sibling definition).
    const isKeptFoamDefinitionAtInsert = existingWikilinkDefinitions.some(
      def =>
        wikilinkLabels.has(def.label) &&
        def.range?.start.line === insertLineIndex
    );
    const prefix = isKeptFoamDefinitionAtInsert ? eol : eol + eol;
    const text = prefix + definitions.join(eol) + eol;

    edits.push({
      range: Range.create(
        insertLineIndex,
        lines[insertLineIndex].length,
        lastLineIndex,
        lines[lastLineIndex].length
      ),
      newText: text,
    });
  }

  return edits;
};
