import { NoteLinkDefinition, Resource, ResourceLink } from '@foam/core';
import { Range } from '@foam/core';
import { createMarkdownReferences } from '@foam/core';
import { FoamWorkspace } from '@foam/core';
import { TextEdit } from '@foam/core';
import { getLinkDefinitions } from '@foam/core';

export const LINK_REFERENCE_DEFINITION_HEADER = `[//begin]: # "Autogenerated link references for markdown compatibility"`;
export const LINK_REFERENCE_DEFINITION_FOOTER = `[//end]: # "Autogenerated link references"`;

export const generateLinkReferences = (
  note: Resource,
  currentNoteText: string,
  eol: string,
  workspace: FoamWorkspace,
  includeExtensions: boolean
): TextEdit[] => {
  const lines = currentNoteText.split(eol);
  const nLines = lines.length;

  const updatedWikilinkDefinitions = createMarkdownReferences(
    workspace,
    note,
    includeExtensions
  );

  const existingWikilinkDefinitions = getLinkDefinitions(currentNoteText);

  const toAddWikilinkDefinitions = updatedWikilinkDefinitions.filter(
    newDef =>
      !existingWikilinkDefinitions.some(
        existingDef => existingDef.label === newDef.label
      )
  );
  const toRemovedWikilinkDefinitions = existingWikilinkDefinitions.filter(
    existingDef => {
      // Keep if it's in the updated set
      if (updatedWikilinkDefinitions.some(newDef => newDef.label === existingDef.label)) {
        return false;
      }
      // Keep if the URL looks like an external resource — even if it's not referenced
      // in the note body (orphan). The rationale is that Foam only manages definitions
      // it creates (relative paths to workspace notes) and should not silently delete
      // user-written external references.
      // NOTE: this is debatable — an unreferenced external definition is arguably dead
      // content and could be cleaned up. Revisit if users find it surprising.
      if (existingDef.url.includes('://')) {
        return false;
      }
      // Keep if a link in the note references this definition label (Option C)
      if (note.links.some(link => ResourceLink.isResolvedReference(link) && link.definition.label === existingDef.label)) {
        return false;
      }
      return true;
    }
  );

  const edits: TextEdit[] = [];

  // Remove old definitions (extend range to consume the trailing newline so no blank line is left)
  for (const def of toRemovedWikilinkDefinitions) {
    edits.push({
      range: Range.create(def.range.start.line, 0, def.range.end.line + 1, 0),
      newText: '',
    });
  }

  // Add new definitions
  if (toAddWikilinkDefinitions.length > 0) {
    // find the last non-empty line to append the definitions after it,
    // skipping lines that are being deleted
    const deletedLines = new Set(
      toRemovedWikilinkDefinitions.map(d => d.range.start.line)
    );
    const lastLineIndex = nLines - 1;
    let insertLineIndex = lastLineIndex;
    while (
      insertLineIndex > 0 &&
      (lines[insertLineIndex].trim() === '' ||
        deletedLines.has(insertLineIndex))
    ) {
      insertLineIndex--;
    }

    const definitions = toAddWikilinkDefinitions.map(def =>
      NoteLinkDefinition.format(def)
    );
    // Collect labels of wikilinks ([[...]]) in the note. These are the only definitions
    // Foam manages directly — regular [text][ref] link references are user-controlled and
    // should still be followed by a blank line before new wikilink definitions.
    const wikilinkLabels = new Set(
      note.links
        .filter(link => link.type === 'wikilink')
        .map(link =>
          link.rawText.substring(link.isEmbed ? 3 : 2, link.rawText.length - 2)
        )
    );
    // Suppress the double-blank-line prefix when appending to an existing Foam-managed
    // wikilink definition block (i.e., the insertion point already has a sibling definition).
    const isKeptFoamDefinitionAtInsert = existingWikilinkDefinitions.some(
      def =>
        wikilinkLabels.has(def.label) &&
        def.range?.start.line === insertLineIndex
    );
    const prefix = isKeptFoamDefinitionAtInsert ? eol : eol + eol;
    const text = prefix + definitions.join(eol) + eol;

    edits.push({
      range: Range.create(
        insertLineIndex,
        lines[insertLineIndex].length,
        lastLineIndex,
        lines[lastLineIndex].length
      ),
      newText: text,
    });
  }

  return edits;
};
