name: Update Docs

on:
  push:
    branches:
      - master
    paths:
      - docs/user/**/*
  workflow_dispatch:

jobs:
  update-docs:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          repository: infogulch/foam-template
          path: foam-template
      - uses: actions/checkout@v3
        with:
          path: foam
      - run: |
          rm -r foam-template/docs
          cp -r foam/docs/user foam-template/docs

          (cd foam-template; git status)
          echo "message=Docs sync @ $(cd foam; git log --pretty='format:%h %s')" >> $GITHUB_OUTPUT          
        id: copy
      - uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.FOAM_DOCS_SYNC_TOKEN }}
          path: foam-template
          commit-message: ${{ steps.copy.outputs.message }}
          branch: bot/foam-docs-sync
          delete-branch: true
          title: Sync docs from foam
          body: Copy docs from main foam repo
